### ISSUE TITLE
Orange color is covering text

### ISSUE THREAD

**Issue by aaronjmichaels** [jamiewilson/predawn-ui#26]
Hey Jamie,

Great theme - my favorite one.  However, on atom there's some issues.  Sometimes the orange background will override text so the text can't be seen - it looks like the text is being changed to the same orange as the background color (for instance, when searching for a file using command T).  Thought you'd want to know.  Doesn't happen in Sublime.

**Comment by jamiewilson** [comment]
Hey @aaronjmichaels thanks for the feedback. Sorry about the issues. I haven't had any time to maintain this version for Atom. If you or anyone you know wants to help with this project, PRs are welcome!

**Comment by dakrisis** [comment]
This bothered me too, Quick fix, by editing the .atom/styles.less within the user folder. just add the following:

```css
@import 'ui-variables';

.list-group li:not(.list-nested-item).selected:before,
.list-tree  li:not(.list-nested-item).selected:before,
.list-group li.list-nested-item.selected > .list-item:before,
.list-tree  li.list-nested-item.selected > .list-item:before {
  background-color: @background-color-selected;
}
```
